name: Remote Deploy

on:
  push:
    branches:
      - main  # Triggers the deployment only on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Execute script on VPS via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22 # Change this if your aaPanel uses a custom SSH port
        script: |
          chmod +x /opt/deploy/deploy-all.sh
          sudo /opt/deploy/deploy-all.sh